insert into DBC.CostProfiles values (26, 'T2_emc', 2, 'F', 'EMC cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (34, 'T2_lsi6285_40', 2, 'F', 'LSI 6285 array with 40 drives cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (4, 'V2R4_Bynet', 1, 'F', 'Bynet cost values for V2R4. Partial profile, bynet values only. '); 
insert into DBC.CostProfiles values (14, 'lsi6840_40', 1, 'F', 'Disk array cost values for LSI 6840 array with 40 drives. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (6, 'V2R5_Bynet_V2', 1, 'F', 'Bynet V2 cost values for V2R5. Partial profile, bynet values only. '); 
insert into DBC.CostProfiles values (28, 'T2_lsi6288_40', 2, 'F', 'LSI 6288 array with 40 drives cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (24, 'T2_symbios_half', 2, 'F', 'Half Populated Symbios 6299 cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (5, 'V2R5_Bynet_V1', 1, 'F', 'Bynet V1 cost values for V2R5. Partial profile, bynet values only. '); 
insert into DBC.CostProfiles values (18, 'V2R4_Array', 1, 'F', 'Disk array cost values for V2R4 Default. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (10, 'lsi6283', 1, 'F', 'Disk array cost values for LSI 6283 array. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (13, 'lsi6840_28', 1, 'F', 'Disk array cost values for LSI 6840 array with 28 drives. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (19, 'V2R5_Array', 1, 'F', 'Disk array cost values for V2R5 Default. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (17, 'lsi6285_40', 1, 'F', 'Disk array cost values for LSI 6285 array with 40 drives. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (29, 'T2_lsi6288_52', 2, 'F', 'LSI 6288 array with 52 drives cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (38, 'T2_TD13_0_LINUX64', 2, 'F', 'Default Type 2 formula parameter initialization values for TD13 on 64 bit Linux platforms. '); 
insert into DBC.CostProfiles values (1, 'V2R4', 1, 'F', 'V2R4 DBS cost values only. Partial profile, no disk array or network values. These use the oldest traditional values and formula in determining query plan costs. '); 
insert into DBC.CostProfiles values (15, 'lsi6840_56', 1, 'F', 'Disk array cost values for LSI 6840 array with 56 drives. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (33, 'T2_lsi6285_20', 2, 'F', 'LSI 6285 array with 20 drives cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (0, 'SysDefault', 1, 'F', 'SysDefault DBS cost values only. Partial profile, no disk array or network values. These use the V2R5 traditional values and formula in determining query plan costs. This is the system standard start of day profile that is shipped by Teradata. Another profile for the system may be selected in dbscontrol. '); 
insert into DBC.CostProfiles values (8, 'symbios_full', 1, 'F', 'Disk array cost values for Fully Populated Symbios 6299. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (11, 'lsi6288_40', 1, 'F', 'Disk array cost values for LSI 6288 array with 40 drives. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (31, 'T2_lsi6840_40', 2, 'F', 'LSI 6840 array with 40 drives cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (23, 'T2_Bynet_V2', 2, 'F', 'Bynet V2 cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (39, 'T2_Bynet_V3', 2, 'F', 'Bynet V3 cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (9, 'emc', 1, 'F', 'Disk array cost values for EMC. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (3, 'V2R5_Solaris', 1, 'F', 'V2R5 DBS cost values only. Specific to Solaris platforms. Partial profile, no disk array or network values. These use the V2R5 traditional values and formula in determining query plan costs. '); 
insert into DBC.CostProfiles values (30, 'T2_lsi6840_28', 2, 'F', 'LSI 6840 array with 28 drives cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (2, 'V2R5', 1, 'F', 'V2R5 DBS cost values only. Partial profile, no disk array or network values. These use the V2R5 traditional values and formula in determining query plan costs. '); 
insert into DBC.CostProfiles values (35, 'V2R6', 1, 'F', 'Generic standard cost profile for V2R6 systems. '); 
insert into DBC.CostProfiles values (32, 'T2_lsi6840_56', 2, 'F', 'LSI 6840 array with 56 drives cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (21, 'T2_Linux64', 2, 'F', 'Default Type 2 formula parameter initialization values for 64 bit Linux platforms. '); 
insert into DBC.CostProfiles values (36, 'Teradata12', 2, 'F', 'Standard cost profile for Teradata12 systems (== T2_32Bit). '); 
insert into DBC.CostProfiles values (25, 'T2_symbios_full', 2, 'F', 'Fully Populated Symbios 6299 cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (37, 'T2_Win64', 2, 'F', 'Default Type 2 formula parameter initialization values for 64 bit Window platforms. '); 
insert into DBC.CostProfiles values (20, 'T2_32Bit', 2, 'F', 'Default Type 2 formula parameter initialization values for 32 bit platforms. '); 
insert into DBC.CostProfiles values (16, 'lsi6285_20', 1, 'F', 'Disk array cost values for LSI 6285 array with 20 drives. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (7, 'symbios_half', 1, 'F', 'Disk array cost values for Half Populated Symbios 6299. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (12, 'lsi6288_52', 1, 'F', 'Disk array cost values for LSI 6288 array with 52 drives. Partial profile, disk array values only. '); 
insert into DBC.CostProfiles values (27, 'T2_lsi6283', 2, 'F', 'LSI 6283 array cost values for Type 2 cost profiles. '); 
insert into DBC.CostProfiles values (22, 'T2_Bynet_V1', 2, 'F', 'Bynet V1 cost values for Type 2 cost profiles. '); 
