CREATE SET TABLE test1 ,NO FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO     (      t1 INTEGER)PRIMARY INDEX ( t1 );
CREATE SET TABLE "test2.test2" ,NO FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO     (      "t2.t2" INTEGER)PRIMARY INDEX ( "t2.t2" );
CREATE SET TABLE test3 ,NO FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO     (      t3 INTEGER)PRIMARY INDEX ( t3 );
CREATE SET TABLE test4 ,NO FALLBACK ,     NO BEFORE JOURNAL,     NO AFTER JOURNAL,     CHECKSUM = DEFAULT,     DEFAULT MERGEBLOCKRATIO     (      t4 VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC)PRIMARY INDEX ( t4 );
create view testView as select t1 from test1;
